[package]
name = "kormen"
version = "0.1.0"
authors = ["oiwn <alex@imscraping.ninja>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
