[package]
name = "kormen"
version = "0.1.1"
authors = ["oiwn <alex@imscraping.ninja>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.8.5"
